# Site settings
title: Statistics Notes
email: 
description: > # this means to ignore newlines until "baseurl:"
  This is an area where I can keep my notes on statistics.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: cieraReports
github_username:  iamciera

# Build settings
markdown: kramdown
